insert into tbl_countries values ('Aruba','AA','AW','U');
insert into tbl_countries values ('United Arab Emirates','AE','AE','U');
insert into tbl_countries values ('Afghanistan','AF','AF','U');
insert into tbl_countries values ('Antigua and Barbuda','AC','AG','U');
insert into tbl_countries values ('Algeria','AG','DZ','N');
insert into tbl_countries values ('Azerbaijan','AJ','AZ','E');
insert into tbl_countries values ('Albania','AL','AL','E');
insert into tbl_countries values ('Armenia','AM','AM','E');
insert into tbl_countries values ('Angola','AO','AO','N');
insert into tbl_countries values ('American Samoa','AQ','AS','U');
insert into tbl_countries values ('Argentina','AR','AR','S');
insert into tbl_countries values ('Ashmore and Cartier Islands','AT','\N','\N');
insert into tbl_countries values ('Australia','AS','AU','U');
insert into tbl_countries values ('Anguilla','AV','AI','U');
insert into tbl_countries values ('Antarctica','AY','AQ','U');
insert into tbl_countries values ('Bahrain','BA','BH','U');
insert into tbl_countries values ('Barbados','BB','BB','U');
insert into tbl_countries values ('Botswana','BC','BW','U');
insert into tbl_countries values ('Austria','AU','AT','E');
insert into tbl_countries values ('Bermuda','BD','BM','U');
insert into tbl_countries values ('Belgium','BE','BE','E');
insert into tbl_countries values ('Bahamas','BF','BS','U');
insert into tbl_countries values ('Bangladesh','BG','BD','U');
insert into tbl_countries values ('Belize','BH','BZ','U');
insert into tbl_countries values ('Bosnia and Herzegovina','BK','BA','E');
insert into tbl_countries values ('Bolivia','BL','BO','U');
insert into tbl_countries values ('Burma','BM','MM','U');
insert into tbl_countries values ('Benin','BN','BJ','N');
insert into tbl_countries values ('Belarus','BO','BY','E');
insert into tbl_countries values ('Solomon Islands','BP','SB','U');
insert into tbl_countries values ('Navassa Island','BQ','\N','\N');
insert into tbl_countries values ('Brazil','BR','BR','U');
insert into tbl_countries values ('Bassas da India','BS','\N','\N');
insert into tbl_countries values ('Bhutan','BT','BT','U');
insert into tbl_countries values ('Bulgaria','BU','BG','E');
insert into tbl_countries values ('Bouvet Island','BV','\N','\N');
insert into tbl_countries values ('Brunei','BX','BN','U');
insert into tbl_countries values ('Burundi','BY','BI','U');
insert into tbl_countries values ('Canada','CA','CA','A');
insert into tbl_countries values ('Cambodia','CB','KH','U');
insert into tbl_countries values ('Chad','CD','TD','N');
insert into tbl_countries values ('Sri Lanka','CE','LK','U');
insert into tbl_countries values ('Congo (Kinshasa)','CF','CD','N');
insert into tbl_countries values ('Congo (Brazzaville)','CG','CG','N');
insert into tbl_countries values ('China','CH','CN','U');
insert into tbl_countries values ('Chile','CI','CL','S');
insert into tbl_countries values ('Cayman Islands','CJ','KY','U');
insert into tbl_countries values ('Cocos (Keeling) Islands','CK','CC','U');
insert into tbl_countries values ('Cameroon','CM','CM','N');
insert into tbl_countries values ('Comoros','CN','KM','U');
insert into tbl_countries values ('Colombia','CO','CO','U');
insert into tbl_countries values ('Northern Mariana Islands','CQ','MP','U');
insert into tbl_countries values ('Coral Sea Islands','CR','\N','\N');
insert into tbl_countries values ('Costa Rica','CS','CR','U');
insert into tbl_countries values ('Central African Republic','CT','CF','N');
insert into tbl_countries values ('Cuba','CU','CU','U');
insert into tbl_countries values ('Cape Verde','CV','CV','U');
insert into tbl_countries values ('Cook Islands','CW','CK','U');
insert into tbl_countries values ('Cyprus','CY','CY','U');
insert into tbl_countries values ('Denmark','DA','DK','E');
insert into tbl_countries values ('Djibouti','DJ','DJ','U');
insert into tbl_countries values ('Dominica','DO','DM','U');
insert into tbl_countries values ('Jarvis Island','DQ','\N','\N');
insert into tbl_countries values ('Dominican Republic','DR','DO','U');
insert into tbl_countries values ('Ecuador','EC','EC','U');
insert into tbl_countries values ('Egypt','EG','EG','U');
insert into tbl_countries values ('Ireland','EI','IE','E');
insert into tbl_countries values ('Equatorial Guinea','EK','GQ','N');
insert into tbl_countries values ('Estonia','EN','EE','E');
insert into tbl_countries values ('Eritrea','ER','ER','U');
insert into tbl_countries values ('El Salvador','ES','SV','U');
insert into tbl_countries values ('Ethiopia','ET','ET','U');
insert into tbl_countries values ('Europa Island','EU','\N','\N');
insert into tbl_countries values ('Czech Republic','EZ','CZ','E');
insert into tbl_countries values ('French Guiana','FG','GF','U');
insert into tbl_countries values ('Finland','FI','FI','E');
insert into tbl_countries values ('Fiji','FJ','FJ','U');
insert into tbl_countries values ('Falkland Islands','FK','FK','U');
insert into tbl_countries values ('Micronesia','FM','FM','U');
insert into tbl_countries values ('Faroe Islands','FO','FO','N');
insert into tbl_countries values ('French Polynesia','FP','PF','U');
insert into tbl_countries values ('Baker Island','FQ','\N','\N');
insert into tbl_countries values ('France','FR','FR','E');
insert into tbl_countries values ('French Southern and Antarctic Lands','FS','\N','\N');
insert into tbl_countries values ('Gambia','GA','GM','N');
insert into tbl_countries values ('Gabon','GB','GA','N');
insert into tbl_countries values ('Georgia','GG','GE','E');
insert into tbl_countries values ('Ghana','GH','GH','N');
insert into tbl_countries values ('Gibraltar','GI','GI','N');
insert into tbl_countries values ('Grenada','GJ','GD','U');
insert into tbl_countries values ('Guernsey','GK','GG','N');
insert into tbl_countries values ('Greenland','GL','GL','U');
insert into tbl_countries values ('Germany','GM','DE','E');
insert into tbl_countries values ('Glorioso Islands','GO','\N','\N');
insert into tbl_countries values ('Guadeloupe','GP','GP','U');
insert into tbl_countries values ('Guam','GQ','GU','U');
insert into tbl_countries values ('Greece','GR','GR','E');
insert into tbl_countries values ('Guatemala','GT','GT','U');
insert into tbl_countries values ('Guinea','GV','GN','N');
insert into tbl_countries values ('Guyana','GY','GY','U');
insert into tbl_countries values ('Gaza Strip','GZ','\N','\N');
insert into tbl_countries values ('Haiti','HA','HT','U');
insert into tbl_countries values ('Hong Kong','HK','HK','U');
insert into tbl_countries values ('Heard Island and McDonald Islands','HM','\N','\N');
insert into tbl_countries values ('Honduras','HO','HN','U');
insert into tbl_countries values ('Howland Island','HQ','\N','\N');
insert into tbl_countries values ('Croatia','HR','HR','E');
insert into tbl_countries values ('Hungary','HU','HU','E');
insert into tbl_countries values ('Iceland','IC','IS','N');
insert into tbl_countries values ('Indonesia','ID','ID','U');
insert into tbl_countries values ('Isle of Man','IM','IM','N');
insert into tbl_countries values ('India','IN','IN','N');
insert into tbl_countries values ('British Indian Ocean Territory','IO','IO','U');
insert into tbl_countries values ('Clipperton Island','IP','\N','\N');
insert into tbl_countries values ('Iran','IR','IR','U');
insert into tbl_countries values ('Israel','IS','IL','U');
insert into tbl_countries values ('Italy','IT','IT','E');
insert into tbl_countries values ('Cote d''Ivoire','IV','IV','N');
insert into tbl_countries values ('Iraq','IZ','IQ','U');
insert into tbl_countries values ('Japan','JA','JP','U');
insert into tbl_countries values ('Jersey','JE','JE','N');
insert into tbl_countries values ('Jamaica','JM','JM','U');
insert into tbl_countries values ('Jan Mayen','JN','\N','\N');
insert into tbl_countries values ('Jordan','JO','JO','E');
insert into tbl_countries values ('Johnston Atoll','JQ','\N','U');
insert into tbl_countries values ('Juan de Nova Island','JU','\N','\N');
insert into tbl_countries values ('Kenya','KE','KE','U');
insert into tbl_countries values ('North Korea','KN','KP','\N');
insert into tbl_countries values ('Kyrgyzstan','KG','KG','U');
insert into tbl_countries values ('Kingman Reef','KQ','\N','\N');
insert into tbl_countries values ('Kiribati','KR','KI','U');
insert into tbl_countries values ('South Korea','KS','KR','U');
insert into tbl_countries values ('Christmas Island','KT','CX','U');
insert into tbl_countries values ('Kuwait','KU','KW','U');
insert into tbl_countries values ('Kazakhstan','KZ','KZ','U');
insert into tbl_countries values ('Laos','LA','LA','U');
insert into tbl_countries values ('Lebanon','LE','LB','E');
insert into tbl_countries values ('Latvia','LG','LV','E');
insert into tbl_countries values ('Lithuania','LH','LT','E');
insert into tbl_countries values ('Liberia','LI','LR','N');
insert into tbl_countries values ('Slovakia','LO','SK','E');
insert into tbl_countries values ('Palmyra Atoll','LQ','\N','\N');
insert into tbl_countries values ('Lesotho','LT','LS','U');
insert into tbl_countries values ('Luxembourg','LU','LU','E');
insert into tbl_countries values ('Libya','LY','LY','N');
insert into tbl_countries values ('Madagascar','MA','MG','U');
insert into tbl_countries values ('Martinique','MB','MQ','U');
insert into tbl_countries values ('Macau','MC','MO','U');
insert into tbl_countries values ('Moldova','MD','MD','E');
insert into tbl_countries values ('Mayotte','MF','YT','U');
insert into tbl_countries values ('Mongolia','MG','MN','U');
insert into tbl_countries values ('Montserrat','MH','MS','N');
insert into tbl_countries values ('Malawi','MI','MW','U');
insert into tbl_countries values ('Montenegro','MJ','ME','E');
insert into tbl_countries values ('Macedonia','MK','MK','E');
insert into tbl_countries values ('Mali','ML','ML','N');
insert into tbl_countries values ('Monaco','MN','MC','E');
insert into tbl_countries values ('Morocco','MO','MA','N');
insert into tbl_countries values ('Mauritius','MP','MU','S');
insert into tbl_countries values ('Midway Islands','MQ','\N','U');
insert into tbl_countries values ('Mauritania','MR','MR','N');
insert into tbl_countries values ('Malta','MT','MT','E');
insert into tbl_countries values ('Oman','MU','OM','U');
insert into tbl_countries values ('Maldives','MV','MV','U');
insert into tbl_countries values ('Mexico','MX','MX','S');
insert into tbl_countries values ('Malaysia','MY','MY','U');
insert into tbl_countries values ('Mozambique','MZ','MZ','U');
insert into tbl_countries values ('New Caledonia','NC','NC','U');
insert into tbl_countries values ('Niue','NE','NU','U');
insert into tbl_countries values ('Norfolk Island','NF','NF','U');
insert into tbl_countries values ('Niger','NG','NE','N');
insert into tbl_countries values ('Vanuatu','NH','VU','U');
insert into tbl_countries values ('Nigeria','NI','NG','N');
insert into tbl_countries values ('Netherlands','NL','NL','E');
insert into tbl_countries values ('Norway','NO','NO','E');
insert into tbl_countries values ('Nepal','NP','NP','N');
insert into tbl_countries values ('Nauru','NR','NR','U');
insert into tbl_countries values ('Suriname','NS','SR','U');
insert into tbl_countries values ('Netherlands Antilles','NT','AN','U');
insert into tbl_countries values ('Nicaragua','NU','NI','U');
insert into tbl_countries values ('New Zealand','NZ','NZ','Z');
insert into tbl_countries values ('Paraguay','PA','PY','S');
insert into tbl_countries values ('Pitcairn Islands','PC','\N','\N');
insert into tbl_countries values ('Peru','PE','PE','U');
insert into tbl_countries values ('Paracel Islands','PF','\N','\N');
insert into tbl_countries values ('Spratly Islands','PG','\N','\N');
insert into tbl_countries values ('Pakistan','PK','PK','U');
insert into tbl_countries values ('Poland','PL','PL','E');
insert into tbl_countries values ('Panama','PM','PA','U');
insert into tbl_countries values ('Portugal','PO','PT','E');
insert into tbl_countries values ('Papua New Guinea','PP','PG','U');
insert into tbl_countries values ('Palau','PS','PW','U');
insert into tbl_countries values ('Guinea-Bissau','PU','GW','N');
insert into tbl_countries values ('Qatar','QA','QA','U');
insert into tbl_countries values ('Serbia','RB','RS','E');
insert into tbl_countries values ('Reunion','RE','\N','U');
insert into tbl_countries values ('Marshall Islands','RM','MH','U');
insert into tbl_countries values ('Romania','RO','RO','E');
insert into tbl_countries values ('Philippines','RP','PH','U');
insert into tbl_countries values ('Puerto Rico','RQ','PR','U');
insert into tbl_countries values ('Russia','RS','RU','E');
insert into tbl_countries values ('Rwanda','RW','RW','U');
insert into tbl_countries values ('Saudi Arabia','SA','SA','U');
insert into tbl_countries values ('Saint Pierre and Miquelon','SB','PM','U');
insert into tbl_countries values ('Saint Kitts and Nevis','SC','KN','U');
insert into tbl_countries values ('Seychelles','SE','SC','U');
insert into tbl_countries values ('South Africa','SF','ZA','U');
insert into tbl_countries values ('Senegal','SG','SN','N');
insert into tbl_countries values ('Saint Helena','SH','SH','N');
insert into tbl_countries values ('Slovenia','SI','SI','E');
insert into tbl_countries values ('Sierra Leone','SL','SL','N');
insert into tbl_countries values ('Singapore','SN','SG','U');
insert into tbl_countries values ('Somalia','SO','SO','U');
insert into tbl_countries values ('Spain','SP','ES','E');
insert into tbl_countries values ('South Sudan','SS','SS','N');
insert into tbl_countries values ('Saint Lucia','ST','LC','U');
insert into tbl_countries values ('Sudan','SU','SD','U');
insert into tbl_countries values ('Svalbard','SV','\N','N');
insert into tbl_countries values ('Sweden','SW','SE','E');
insert into tbl_countries values ('South Georgia and the Islands','SX','\N','\N');
insert into tbl_countries values ('Syria','SY','SY','E');
insert into tbl_countries values ('Switzerland','SZ','CH','E');
insert into tbl_countries values ('Trinidad and Tobago','TD','TT','U');
insert into tbl_countries values ('Tromelin Island','TE','\N','\N');
insert into tbl_countries values ('Thailand','TH','TH','U');
insert into tbl_countries values ('Tajikistan','TI','TJ','U');
insert into tbl_countries values ('Turks and Caicos Islands','TK','TC','U');
insert into tbl_countries values ('Tokelau','TL','TK','\N');
insert into tbl_countries values ('Tonga','TN','TO','U');
insert into tbl_countries values ('Togo','TO','TG','N');
insert into tbl_countries values ('Sao Tome and Principe','TP','\N','N');
insert into tbl_countries values ('Tunisia','TS','TN','E');
insert into tbl_countries values ('Timor-Leste','TT','TL','\N');
insert into tbl_countries values ('Turkey','TU','TR','E');
insert into tbl_countries values ('Tuvalu','TV','TV','U');
insert into tbl_countries values ('Taiwan','TW','TW','U');
insert into tbl_countries values ('Turkmenistan','TX','TM','U');
insert into tbl_countries values ('Tanzania','TZ','TZ','U');
insert into tbl_countries values ('Uganda','UG','UG','U');
insert into tbl_countries values ('United Kingdom','UK','GB','E');
insert into tbl_countries values ('Ukraine','UP','UA','E');
insert into tbl_countries values ('United States','US','US','A');
insert into tbl_countries values ('Burkina Faso','UV','BF','N');
insert into tbl_countries values ('Uruguay','UY','UY','S');
insert into tbl_countries values ('Uzbekistan','UZ','UZ','U');
insert into tbl_countries values ('Saint Vincent and the Grenadines','VC','VC','U');
insert into tbl_countries values ('Venezuela','VE','VE','U');
insert into tbl_countries values ('British Virgin Islands','VI','VG','U');
insert into tbl_countries values ('Vietnam','VM','VN','U');
insert into tbl_countries values ('Virgin Islands','VQ','\N','U');
insert into tbl_countries values ('Namibia','WA','NA','N');
insert into tbl_countries values ('West Bank','WE','\N','U');
insert into tbl_countries values ('Wallis and Futuna','WF','WF','U');
insert into tbl_countries values ('Western Sahara','WI','EH','N');
insert into tbl_countries values ('Wake Island','WQ','\N','\N');
insert into tbl_countries values ('Samoa','WS','WS','U');
insert into tbl_countries values ('Swaziland','WZ','SZ','U');
insert into tbl_countries values ('Yemen','YM','YE','U');
insert into tbl_countries values ('Zambia','ZA','ZM','U');
insert into tbl_countries values ('Zimbabwe','ZI','ZW','U');
